### ISSUE TITLE
App goes blank

### ISSUE THREAD

**Issue by bminick** [zendesklabs/project_app#45] opened 2018-01-11 20:54 UTC
Hi,

First, I want to say thank you for building and working on this app. My organization leans heavily on it and it is a big part of our zendesk workflows. It looks like you are making some updates to the app which is great. But we've had a few issues along the way.

Our users are reporting that many times the tickets are not being displayed and it's almost as if the app goes blank. I have a few screenshots for you here: https://www.screencast.com/t/iGcFnmhs

Sometimes the team is reporting if they refresh quite a few times it will come up.

The team is also reporting many times it does not bring over the ticket information. See below
https://www.screencast.com/t/CICvNf1lPq

Note, we renamed it to parent/child tickets.

Is there anyway to publish a old version that we could install and leave running while you work on your improvements? Do you mind sharing what improvements you are working on?

Thanks again for building this app, it's great and we love it.

**Comment by skipjac** [comment] 2018-01-11 22:02
I will look into the date issue, the reason for the update is in order to add brand to the form it had to be updated to v2. So this is just suppose to be a straight conversion using the new framework it was working until I fixed for customers without ticket forms. then things are getting strange. 

I will keep at trying to replicate and fix the issues.

**Comment by bminick** [comment] 2018-01-11 22:22
Thanks, if there's anything I can do to help give feedback feel free to comment here and ill get back to you promptly.

Thanks again

**Comment by bminick** [comment] 2018-01-19 22:02
Hey Skip, our issues appear to be getting worse. We are refreshing ~5x just to get tickets to show up in the app. Otherwise, it's just blank like the screenshots above.

Also, our agents need to toggle between create single/bulk in order for all the fields to show. As an example, if you click create bulk, it will be missing some fields, but then if you change it to single, the fields will all appear.

We've also seen tickets being created, but then not showing up on the list and we need to go back and link an existing ticket.

If it matters, we are on a enterprise plan and use 10 different ticket forms in ZenDesk. Appreciate your help.

**Comment by skipjac** [comment] 2018-01-19 23:26
Hey, while I am seeing the blanking issue sometimes, it doesn't sound as bad as you are seeing. What browser are you using?

**Comment by bminick** [comment] 2018-01-22 15:56
We use Chrome across the board. A mix between Windows and OSX users however. I am trying to see if I can get someone to record it in action so you can see (if it would help).

**Comment by bminick** [comment] 2018-02-01 19:46
Hey Skip was wondering if you may have been able to see what's up? Or if it would be possible to publish a previously stable version that I could use in the meantime? Appreciate your help.

**Comment by Loopercal** [comment] 2018-02-08 11:31
Hi Skip,

Just to chip in, we are seeing the same behavior as bminick and his folks. We mostly use Firefox, but I know for a fact multiple agents prefer Chrome as well.

Any plans on resolving this? Is there anything we can do to help you on this matter?

**Comment by skipjac** [comment] 2018-02-08 16:59
Any logs or screencasts would be great. I have been pushing updates trying to increase stability. I am just not seeing the data not transfer issue at all. And I can only get it not to load 1 of 50 times. So it makes it hard to troubleshoot

**Comment by Loopercal** [comment] 2018-02-08 17:10
Hi Skip,

Roger that, will try to acquire the same tomorrow. I am also having suspicion that this behavior is somehow caused by Zendesk itself, as all of this happened when they deployed general app update exactly a month ago. Remember we also reported app color issues.

Talk to you tomorrow, thanks.

**Comment by bminick** [comment] 2018-02-21 15:41
Hey Skip, any progress on trying to get any of these issues resolved?

**Comment by skipjac** [comment] 2018-02-22 15:18
Working on it, I have another dev looking into it doing a code review

**Comment by bminick** [comment] 2018-03-02 16:59
Skip is there anything we can do to help? The team is still heavily complaining about the app not showing and constantly needing to refresh.

I really appreciate it.

**Comment by skipjac** [comment] 2018-06-13 16:11
Is the blank app problem still a issue?

**Comment by bminick** [comment] 2018-06-13 17:17
I have not had any issues with this lately. I would say this is resolved.

**Closed** 2018-06-13 17:53 UTC
